# Generated by Django 3.2.9 on 2021-12-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('discreption', models.TextField(max_length=200)),
                ('is_open', models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=False, verbose_name='IsOpen')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='image')),
                ('discreption', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('foodcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_category', to='resturant.category')),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food', to='resturant.food')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('delivery_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Order', 'Order'), ('Peyment', 'Peyment'), ('Send', 'Send'), ('Delivery', 'Delivery')], default='Order', max_length=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customeraddress_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customeradress')),
                ('food_menu_id', models.ManyToManyField(to='resturant.FoodMenu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('food_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodmenu', to='resturant.foodmenu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='resturant.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_item_id',
            field=models.ManyToManyField(related_name='order_item_id', to='resturant.OrderItem', verbose_name='order_item'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='resturant.branch')),
            ],
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='resturant.menu'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal_id',
            field=models.ManyToManyField(related_name='meal', to='resturant.Meal'),
        ),
        migrations.AddField(
            model_name='food',
            name='menu_id',
            field=models.ManyToManyField(related_name='food_menu', through='resturant.FoodMenu', to='resturant.Menu'),
        ),
        migrations.AddField(
            model_name='branch',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_branch', to='resturant.category'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maneger', to='accounts.manager', verbose_name='which_manager'),
        ),
    ]
