# Generated by Django 3.2.9 on 2021-12-31 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='food',
            name='branch_id',
            field=models.ManyToManyField(related_name='food_menu', through='resturant.FoodMenu', to='resturant.Branch'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_id', to='resturant.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='foodmenu_id',
            field=models.ManyToManyField(related_name='food', through='resturant.OrderItem', to='resturant.FoodMenu'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(1, 'Close'), (0, 'Open')], default=False, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foodmenu', to='resturant.foodmenu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
