# Generated by Django 3.2.9 on 2021-12-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20211231_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_id',
            field=models.ManyToManyField(related_name='food_meal', to='resturant.Food'),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=False, verbose_name='IsOpen'),
        ),
    ]
