# Generated by Django 3.2.9 on 2022-01-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_auto_20220101_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=False, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
