# Generated by Django 3.2.9 on 2022-01-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_device'),
        ('resturant', '0005_auto_20220101_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(1, 'Close'), (0, 'Open')], default=False, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customeraddress_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumer_address', to='accounts.customeradress'),
        ),
    ]
