# Generated by Django 3.2.9 on 2022-01-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_auto_20220101_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_menu_id',
        ),
    ]
