# Generated by Django 3.2.9 on 2022-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0008_remove_meal_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=False, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
