# Generated by Django 3.2.9 on 2022-01-03 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0009_auto_20220101_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
