# Generated by Django 3.2.9 on 2022-01-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0012_auto_20220103_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(1, 'Close'), (0, 'Open')], default=False, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='resturant.branch'),
        ),
    ]
