# Generated by Django 3.2.9 on 2022-01-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220104_1047'),
        ('resturant', '0014_alter_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Branch',
            name='manager_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maneger', to='accounts.manager', verbose_name='which_manager'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=False, verbose_name='IsOpen'),
        ),
    ]
