# Generated by Django 3.2.9 on 2022-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0015_auto_20220104_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='foods',
            field=models.ManyToManyField(related_name='food_menu', through='resturant.FoodMenu', to='resturant.Food'),
        ),
    ]
