# Generated by Django 3.2.9 on 2022-01-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0016_auto_20220104_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(1, 'Close'), (0, 'Open')], default=False, verbose_name='IsOpen'),
        ),
    ]
