# Generated by Django 3.2.9 on 2022-01-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220115_2215'),
        ('resturant', '0019_alter_branch_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(choices=[(0, 'Open'), (1, 'Close')], default=True, verbose_name='IsOpen'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='maneger', to='accounts.manager', verbose_name='which_manager'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=30, verbose_name='resturant name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='foodmenu_id',
            field=models.ManyToManyField(null=True, related_name='food', through='resturant.OrderItem', to='resturant.FoodMenu'),
        ),
    ]
