# Generated by Django 3.2.9 on 2022-01-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220104_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customeraddress_id',
        ),
        migrations.AddField(
            model_name='customeradress',
            name='customer',
            field=models.ManyToManyField(related_name='customer_address', to='accounts.Customer'),
        ),
    ]
