# Generated by Django 3.2.9 on 2022-01-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220106_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeradress',
            options={'ordering': ['pk'], 'verbose_name': 'customerAddress'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.ManyToManyField(related_name='address', through='accounts.CustomerAdress', to='accounts.Customer'),
        ),
    ]
