# Generated by Django 3.2.9 on 2022-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_address_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(related_name='address', through='accounts.CustomerAdress', to='accounts.Address'),
        ),
    ]
