# Generated by Django 3.2.9 on 2022-01-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220106_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer1', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='customeradress',
            name='default',
            field=models.BooleanField(),
        ),
    ]
